# Generated by Django 6.1 on 2026-08-11 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='core.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stores', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به فروشگاه',
                'verbose_name_plural': 'دسترسی کاربران به فروشگاه\u200cها',
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='unique_user_store')],
            },
        ),
    ]
