# Generated by Django 6.1 on 2026-08-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر فروشگاه'), ('seller', 'فروشنده'), ('cashier', 'صندوقدار'), ('warehouse', 'انباردار')], default='seller', max_length=20, verbose_name='نقش'),
        ),
    ]
