# Generated by Django 6.1 on 2026-08-14 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'خرید'), ('payment', 'پرداخت'), ('return', 'برگشت خرید'), ('adjustment', 'اصلاح حساب')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.supplier')),
            ],
            options={
                'verbose_name': 'تراکنش تأمین\u200cکننده',
                'verbose_name_plural': 'تراکنش\u200cهای تأمین\u200cکنندگان',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
