# Generated by Django 6.1 on 2026-08-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0009_purchasereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.store', verbose_name='فروشگاه'),
        ),
    ]
