# Generated by Django 6.1 on 2026-08-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0010_supplier_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.store', verbose_name='فروشگاه'),
        ),
    ]
