# Generated by Django 6.1 on 2026-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0011_alter_supplier_store'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_supplier_name_per_store'),
        ),
    ]
