# Generated by Django 6.1 on 2026-09-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_final_integrity_sweep'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productprice',
            name='product_price_amount_gt_zero',
        ),
    ]
