# Generated by Django 6.1 on 2026-09-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_integrity_constraint_reconciliation'),
        ('products', '0024_remove_productprice_product_price_amount_gt_zero'),
    ]

    operations = [
    ]
