import { useEffect,useMemo,useState } from "react";
import { Alert,Box,Button,Card,CardContent,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Select,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography,Chip } from "@mui/material";
import { useStore } from "../../contexts/StoreContext";
import { listInventory } from "../../services/inventoryService";
import { approveTransfer,cancelTransfer,createTransfer,listTransfers,receiveTransfer,shipTransfer,type StockTransfer } from "../../services/transferService";
import type { InventoryItem } from "../../services/inventoryService";
const err=(e:any)=>e?.response?.data?.detail||e?.response?.data?.items||e?.response?.data?.message||"عملیات انجام نشد.";
const statusColor=(s:string)=>s==="received"?"success":s==="cancelled"?"error":s==="shipped"?"info":s==="approved"?"warning":"default";
export default function StockTransfers(){
 const {stores,activeStore,activeRole}=useStore(); const [rows,setRows]=useState<StockTransfer[]>([]); const [inventory,setInventory]=useState<InventoryItem[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [open,setOpen]=useState(false); const [destination,setDestination]=useState(""); const [product,setProduct]=useState(""); const [qty,setQty]=useState(""); const [notes,setNotes]=useState("");
 const accessible=useMemo(()=>stores.filter(s=>s.is_active&&s.id!==activeStore?.id),[stores,activeStore?.id]);
 const load=async()=>{if(!activeStore)return;setLoading(true);try{setRows(await listTransfers(activeStore.id));setInventory(await listInventory(activeStore.id));}catch(e){setError(err(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[activeStore?.id]);
 const submit=async()=>{if(!activeStore||!destination||!product||!qty)return;try{await createTransfer(activeStore.id,Number(destination),Number(product),qty,notes);setOpen(false);setDestination("");setProduct("");setQty("");setNotes("");await load()}catch(e){setError(err(e))}};
 const action=async(fn:(id:number)=>Promise<any>,id:number)=>{try{await fn(id);await load()}catch(e){setError(err(e))}};
 if(!activeStore)return <Alert severity="warning">ابتدا فروشگاه را انتخاب کنید.</Alert>;
 return <Box dir="rtl"><Stack direction={{xs:"column",sm:"row"}} sx={{mb:2,justifyContent:"space-between",alignItems:"center"}}><Box><Typography variant="h5" sx={{fontWeight:700}}>انتقال کالا بین شعب</Typography><Typography color="text.secondary">انتقال کنترل‌شده موجودی با تأیید، ارسال و دریافت</Typography></Box><Button variant="contained" onClick={()=>setOpen(true)} disabled={!accessible.length}>انتقال جدید</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError("")}>{String(error)}</Alert>}{loading?<CircularProgress/>:<Card><CardContent><Table size="small"><TableHead><TableRow><TableCell>شماره</TableCell><TableCell>مبدأ</TableCell><TableCell>مقصد</TableCell><TableCell>کالا</TableCell><TableCell>مقدار</TableCell><TableCell>وضعیت</TableCell><TableCell>عملیات</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell>#{r.id}</TableCell><TableCell>{r.source_store_name}</TableCell><TableCell>{r.destination_store_name}</TableCell><TableCell>{r.items.map(i=>i.product_name).join("، ")||"-"}</TableCell><TableCell>{r.items.map(i=>i.quantity).join("، ")||"-"}</TableCell><TableCell><Chip size="small" label={r.status_display} color={statusColor(r.status) as any}/></TableCell><TableCell>{r.status==="draft"&&activeRole==="manager"&&<Button size="small" onClick={()=>void action(approveTransfer,r.id)}>تأیید</Button>}{r.status==="approved"&&(activeRole==="manager"||activeRole==="warehouse")&&r.source_store===activeStore.id&&<Button size="small" onClick={()=>void action(shipTransfer,r.id)}>ارسال</Button>}{r.status==="shipped"&&(activeRole==="manager"||activeRole==="warehouse")&&r.destination_store===activeStore.id&&<Button size="small" onClick={()=>void action(receiveTransfer,r.id)}>دریافت</Button>}{["draft","approved"].includes(r.status)&&activeRole==="manager"&&r.source_store===activeStore.id&&<Button size="small" color="error" onClick={()=>void action(cancelTransfer,r.id)}>لغو</Button>}</TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={7} align="center">انتقالی ثبت نشده است.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>}
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>ثبت انتقال جدید از {activeStore.name}</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><Select value={destination} displayEmpty onChange={e=>setDestination(e.target.value)}><MenuItem value="">انتخاب فروشگاه مقصد</MenuItem>{accessible.map(s=><MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</Select><Select value={product} displayEmpty onChange={e=>setProduct(e.target.value)}><MenuItem value="">انتخاب کالا</MenuItem>{inventory.filter(i=>Number(i.quantity)>0).map(i=><MenuItem key={i.product} value={i.product}>{i.product_name} — موجودی {i.quantity}</MenuItem>)}</Select><TextField label="مقدار انتقال" type="number" value={qty} onChange={e=>setQty(e.target.value)} slotProps={{ htmlInput: { min: 0.001, step: 0.001 } }}/><TextField label="توضیحات" value={notes} onChange={e=>setNotes(e.target.value)}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>انصراف</Button><Button variant="contained" onClick={()=>void submit()}>ثبت انتقال</Button></DialogActions></Dialog>
 </Box>
}
