import { useEffect,useState } from "react";
import { Alert,Box,Button,Card,CardContent,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add"; import EditIcon from "@mui/icons-material/Edit"; import DeleteIcon from "@mui/icons-material/Delete"; import HistoryIcon from "@mui/icons-material/History";
import { useStore } from "../../contexts/StoreContext"; import { listSuppliers,createSupplier,updateSupplier,deleteSupplier,supplierLedger,type Supplier,type SupplierTx } from "../../services/supplierService";
const money=(v:any)=>Number(v||0).toLocaleString("fa-IR"); const err=(e:any)=>e?.response?.data?.detail||e?.response?.data?.message||"عملیات انجام نشد.";
export default function Suppliers(){ const {activeStore,activeRole}=useStore(); const [items,setItems]=useState<Supplier[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [editing,setEditing]=useState<Supplier|null>(null); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [address,setAddress]=useState(""); const [description,setDescription]=useState(""); const [ledger,setLedger]=useState<SupplierTx[]>([]); const [ledgerTitle,setLedgerTitle]=useState("");
 const load=async()=>{if(!activeStore)return;setLoading(true);try{setItems(await listSuppliers(activeStore.id))}catch(e){setError(err(e))}finally{setLoading(false)}}; useEffect(()=>{void load()},[activeStore?.id]);
 const form=(s?:Supplier)=>{setEditing(s||null);setName(s?.name||"");setPhone(s?.phone||"");setAddress(s?.address||"");setDescription(s?.description||"");setOpen(true)};
 const save=async()=>{if(!activeStore||!name.trim())return;try{if(editing)await updateSupplier(editing.id,{name,phone,address,description});else await createSupplier({store:activeStore.id,name,phone,address,description});setOpen(false);await load()}catch(e){setError(err(e))}};
 const showLedger=async(s:Supplier)=>{try{const data=await supplierLedger(s.id);setLedger(Array.isArray(data)?data:data.results);setLedgerTitle(s.name)}catch(e){setError(err(e))}};
 const remove=async(s:Supplier)=>{if(activeRole!=="manager"||!confirm(`تأمین‌کننده «${s.name}» حذف شود؟`))return;try{await deleteSupplier(s.id);await load()}catch(e){setError(err(e))}};
 if(!activeStore)return <Alert severity="warning">ابتدا فروشگاه را انتخاب کنید.</Alert>; return <Box dir="rtl"><Stack direction="row" sx={{mb:2,justifyContent:"space-between",alignItems:"center"}}><Box><Typography variant="h5" sx={{fontWeight:700}}>تأمین‌کنندگان</Typography><Typography color="text.secondary">مدیریت طرف حساب خرید و بدهی تأمین‌کنندگان</Typography></Box><Button startIcon={<AddIcon/>} variant="contained" onClick={()=>form()}>تأمین‌کننده جدید</Button></Stack>{error&&<Alert sx={{mb:2}} severity="error">{error}</Alert>}{loading?<CircularProgress/>:<Card><CardContent><TableContainer><Table><TableHead><TableRow><TableCell>نام</TableCell><TableCell>تلفن</TableCell><TableCell>آدرس</TableCell><TableCell>عملیات</TableCell></TableRow></TableHead><TableBody>{items.map(s=><TableRow key={s.id} hover><TableCell sx={{fontWeight:600}}>{s.name}</TableCell><TableCell>{s.phone||"-"}</TableCell><TableCell>{s.address||"-"}</TableCell><TableCell><IconButton onClick={()=>void showLedger(s)}><HistoryIcon/></IconButton><IconButton onClick={()=>form(s)}><EditIcon/></IconButton>{activeRole==="manager"&&<IconButton color="error" onClick={()=>void remove(s)}><DeleteIcon/></IconButton>}</TableCell></TableRow>)}{!items.length&&<TableRow><TableCell colSpan={4} align="center">تأمین‌کننده‌ای ثبت نشده است.</TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card>}
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing?"ویرایش تأمین‌کننده":"ثبت تأمین‌کننده"}</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField label="نام" value={name} onChange={e=>setName(e.target.value)} required/><TextField label="تلفن" value={phone} onChange={e=>setPhone(e.target.value)}/><TextField label="آدرس" value={address} onChange={e=>setAddress(e.target.value)}/><TextField label="توضیحات" value={description} onChange={e=>setDescription(e.target.value)} multiline/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>انصراف</Button><Button variant="contained" onClick={()=>void save()}>ذخیره</Button></DialogActions></Dialog>
 <Dialog open={!!ledgerTitle} onClose={()=>setLedgerTitle("")} fullWidth maxWidth="md"><DialogTitle>گردش حساب {ledgerTitle}</DialogTitle><DialogContent><Table size="small"><TableHead><TableRow><TableCell>نوع</TableCell><TableCell>مبلغ</TableCell><TableCell>شرح</TableCell><TableCell>تاریخ</TableCell></TableRow></TableHead><TableBody>{ledger.map(t=><TableRow key={t.id}><TableCell><Chip label={t.transaction_type==="purchase"?"خرید":t.transaction_type==="payment"?"پرداخت":"برگشت"}/></TableCell><TableCell>{money(t.amount)}</TableCell><TableCell>{t.description||"-"}</TableCell><TableCell>{t.created_at}</TableCell></TableRow>)}</TableBody></Table></DialogContent></Dialog></Box> }
