# Generated by Django 6.1 on 2026-08-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0007_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashboxes', to='core.store')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashBoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('receive', 'دریافت'), ('payment', 'پرداخت')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.cashbox')),
            ],
            options={
                'verbose_name': 'تراکنش صندوق',
                'verbose_name_plural': 'تراکنش\u200cهای صندوق',
                'ordering': ['-created_at'],
            },
        ),
    ]
