import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Card, CardContent, CircularProgress, Divider, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
import RefreshIcon from "@mui/icons-material/Refresh";
import { useStore } from "../contexts/StoreContext";
import JalaliDateInput from "../components/JalaliDateInput";
import { jalaliDateToIsoDate, todayJalali, toJalali, formatJalali } from "../utils/jalaliDate";
import { cashFinancialReport, cashLedger, cashboxBalanceReport, dailyCashFlowReport, financialSummary, type CashBoxBalanceRow, type CashLedgerRow, type DailyCashFlowRow, type FinancialCashFlow, type FinancialSummary } from "../services/reportService";
import { getApiErrorMessage as err } from "../utils/apiError";

const money=(v:string|number)=>Number(v||0).toLocaleString("fa-IR");

export default function FinancialReports(){
 const {activeStore,activeRole}=useStore();
 const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const [summary,setSummary]=useState<FinancialSummary|null>(null); const [flow,setFlow]=useState<FinancialCashFlow|null>(null); const [ledger,setLedger]=useState<CashLedgerRow[]>([]); const [boxes,setBoxes]=useState<CashBoxBalanceRow[]>([]); const [daily,setDaily]=useState<DailyCashFlowRow[]>([]);
 const params=useMemo(()=>({store:activeStore?.id,start_date:start?jalaliDateToIsoDate(start):undefined,end_date:end?jalaliDateToIsoDate(end):undefined}),[activeStore?.id,start,end]);
 const load=async()=>{if(!activeStore)return;setLoading(true);setError("");try{const [s,f,l,b,d]=await Promise.all([financialSummary(params),cashFinancialReport(params),cashLedger(params),cashboxBalanceReport(params),dailyCashFlowReport(params)]);setSummary(s);setFlow(f);setLedger(l);setBoxes(b);setDaily(d);}catch(e){setError(err(e));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[activeStore?.id]);
 const range=(kind:"today"|"month"|"all")=>{if(kind==="all"){setStart("");setEnd("");return;}const n=new Date();const j=toJalali(n.getFullYear(),n.getMonth()+1,n.getDate());setEnd(formatJalali(j.jy,j.jm,j.jd));setStart(kind==="today"?todayJalali():formatJalali(j.jy,j.jm,1));};
 if(!activeStore)return <Alert severity="warning">ابتدا یک فروشگاه انتخاب کنید.</Alert>;
 if(activeRole!=="manager"&&activeRole!=="cashier")return <Alert severity="warning">دسترسی به گزارش مالی و صندوق برای این نقش فعال نیست.</Alert>;
 return <Box dir="rtl"><Stack direction={{xs:"column",md:"row"}} sx={{justifyContent:"space-between",alignItems:{md:"center"},mb:2,gap:1}}><Box><Typography variant="h5" sx={{fontWeight:800}}>گزارش مالی و گردش صندوق</Typography><Typography color="text.secondary">خلاصه مالی، دریافت و پرداخت، مانده صندوق و گردش روزانه</Typography></Box><Button variant="contained" startIcon={<RefreshIcon/>} onClick={()=>void load()} disabled={loading}>به‌روزرسانی</Button></Stack>
 <Card sx={{mb:2}}><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={1.5} sx={{alignItems:{md:"center"}}}><JalaliDateInput label="از تاریخ" value={start} onChange={setStart} allowClear/><JalaliDateInput label="تا تاریخ" value={end} onChange={setEnd} allowClear/><Button size="small" variant="outlined" onClick={()=>range("today")}>امروز</Button><Button size="small" variant="outlined" onClick={()=>range("month")}>این ماه</Button><Button size="small" variant="outlined" onClick={()=>range("all")}>همه</Button><Button variant="outlined" onClick={()=>void load()} disabled={loading}>اعمال</Button></Stack></CardContent></Card>
 {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{loading&&!summary?<Box sx={{display:"grid",placeItems:"center",minHeight:280}}><CircularProgress/></Box>:<Stack spacing={2}>
 <Stack direction={{xs:"column",md:"row"}} spacing={2}>{[["فروش",summary?.sales],["بهای تمام‌شده",summary?.cost_of_goods_sold],["سود ناخالص",summary?.gross_profit],["هزینه‌ها",summary?.expenses],["سود خالص",summary?.net_profit],["مطالبات مشتریان",summary?.customer_receivable],["بدهی تأمین‌کنندگان",summary?.supplier_payable],["مانده صندوق",summary?.cash_balance]].map(([t,v])=><Card key={String(t)} sx={{flex:1,minWidth:150}}><CardContent><Typography variant="body2" color="text.secondary">{t}</Typography><Typography variant="h6" sx={{fontWeight:800,mt:1}}>{money((v as string|number) || 0)}</Typography></CardContent></Card>)}</Stack>
 <Card><CardContent><Typography variant="h6" sx={{fontWeight:700}}>دریافت و پرداخت</Typography><Divider sx={{my:1}}/><Stack direction={{xs:"column",sm:"row"}} spacing={3}><Typography>دریافت: <b>{money(flow?.receipts||0)}</b></Typography><Typography>پرداخت: <b>{money(flow?.payments||0)}</b></Typography><Typography>خالص گردش: <b>{money(flow?.net_cash_flow||0)}</b></Typography></Stack></CardContent></Card>
 <Card><CardContent><Typography variant="h6" sx={{fontWeight:700,mb:1}}>مانده صندوق‌ها</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>صندوق</TableCell><TableCell>فروشگاه</TableCell><TableCell>مانده</TableCell><TableCell>تراکنش</TableCell><TableCell>دریافت</TableCell><TableCell>پرداخت</TableCell></TableRow></TableHead><TableBody>{boxes.map(x=><TableRow key={x.id}><TableCell>{x.name}</TableCell><TableCell>{x.store}</TableCell><TableCell>{money(x.balance)}</TableCell><TableCell>{x.transaction_count}</TableCell><TableCell>{x.receive_count}</TableCell><TableCell>{x.payment_count}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 <Card><CardContent><Typography variant="h6" sx={{fontWeight:700,mb:1}}>گردش روزانه صندوق</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>روز</TableCell><TableCell>تراکنش</TableCell><TableCell>دریافت</TableCell><TableCell>پرداخت</TableCell><TableCell>خالص</TableCell></TableRow></TableHead><TableBody>{daily.map(x=><TableRow key={x.day}><TableCell>{x.day}</TableCell><TableCell>{x.transaction_count}</TableCell><TableCell>{money(x.receipts)}</TableCell><TableCell>{money(x.payments)}</TableCell><TableCell>{money(x.net_cash_flow)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 <Card><CardContent><Typography variant="h6" sx={{fontWeight:700,mb:1}}>دفتر گردش صندوق</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>صندوق</TableCell><TableCell>نوع</TableCell><TableCell>مبلغ</TableCell><TableCell>شرح</TableCell><TableCell>مرجع</TableCell></TableRow></TableHead><TableBody>{ledger.slice(0,100).map(x=><TableRow key={x.id}><TableCell>{x.cashbox}</TableCell><TableCell>{x.type}</TableCell><TableCell>{money(x.amount)}</TableCell><TableCell>{x.description||"-"}</TableCell><TableCell>{x.reference_id??"-"}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 </Stack>}</Box>;
}