import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, FormControl, InputLabel, MenuItem, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
import RefreshIcon from "@mui/icons-material/Refresh";
import TrendingUpIcon from "@mui/icons-material/TrendingUp";
import PaymentsIcon from "@mui/icons-material/Payments";
import AccountBalanceWalletIcon from "@mui/icons-material/AccountBalanceWallet";
import CancelIcon from "@mui/icons-material/Cancel";
import { useStore } from "../contexts/StoreContext";
import { cashReconciliation, cancellationsReport, dailySales, financialReport, monthlySales, paymentMethods, summaryReport, topProducts, type Cancellation, type CashRecon, type Daily, type Financial, type Monthly, type PaymentMethod, type Summary, type TopProduct } from "../services/reportService";

const money = (v: string | number) => Number(v || 0).toLocaleString("fa-IR");
const compactMoney = (v: string | number) => Number(v || 0).toLocaleString("fa-IR", { notation: "compact", maximumFractionDigits: 1 });
const errorMessage = (e: any) => e?.response?.data?.detail || e?.response?.data?.message || (typeof e?.response?.data === "string" ? e.response.data : "دریافت گزارش‌ها انجام نشد.");
const iso = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;

function Kpi({ title, value, icon, caption }: { title: string; value: string; icon: React.ReactNode; caption?: string }) {
  return <Card sx={{ flex: 1, minWidth: 190 }}><CardContent><Stack direction="row" sx={{ justifyContent: "space-between", alignItems: "flex-start" }}><Box><Typography variant="body2" color="text.secondary">{title}</Typography><Typography variant="h5" sx={{ fontWeight: 800,  mt: 1 }}>{value}</Typography>{caption && <Typography variant="caption" color="text.secondary">{caption}</Typography>}</Box><Box sx={{ p: 1.1, borderRadius: 2, bgcolor: "action.hover" }}>{icon}</Box></Stack></CardContent></Card>;
}

function TrendChart({ rows }: { rows: Daily[] }) {
  const points = [...rows].reverse().slice(-14); if (!points.length) return <Box sx={{ py: 5, textAlign: "center" }}><Typography color="text.secondary">داده‌ای برای نمودار وجود ندارد.</Typography></Box>;
  const max = Math.max(...points.map(x => Number(x.total_sales)), 1); const w = 720, h = 230, pad = 28;
  const xy = points.map((p, i) => { const x = pad + (i * (w - pad * 2)) / Math.max(points.length - 1, 1); const y = h - pad - (Number(p.total_sales) / max) * (h - pad * 2); return { x, y, label: p.day, value: Number(p.total_sales) }; });
  const path = xy.map((p, i) => `${i ? "L" : "M"}${p.x},${p.y}`).join(" ");
  return <Box sx={{ width: "100%", overflowX: "auto" }}><svg viewBox={`0 0 ${w} ${h}`} width="100%" height="230" role="img" aria-label="روند فروش روزانه"><line x1={pad} y1={h-pad} x2={w-pad} y2={h-pad} stroke="currentColor" opacity=".15" /><path d={path} fill="none" stroke="currentColor" strokeWidth="3" /><path d={`${path} L${xy[xy.length-1].x},${h-pad} L${xy[0].x},${h-pad} Z`} fill="currentColor" opacity=".07" />{xy.map((p, i) => <g key={`${p.label}-${i}`}><circle cx={p.x} cy={p.y} r="4" fill="currentColor" /><text x={p.x} y={h-7} textAnchor="middle" fontSize="11" fill="currentColor" opacity=".65">{String(p.label).slice(5)}</text></g>)}</svg></Box>;
}

function PaymentMix({ rows, summary }: { rows: PaymentMethod[]; summary: Summary | null }) {
  const values = rows.length ? rows : [
    { method: "cash", method_name: "نقدی", amount: summary?.cash || "0", transaction_count: 0 },
    { method: "card", method_name: "کارتخوان", amount: summary?.card || "0", transaction_count: 0 },
    { method: "credit", method_name: "اعتباری", amount: summary?.credit || "0", transaction_count: 0 },
  ];
  const total = values.reduce((a, x) => a + Number(x.amount), 0); const segments = values.map(x => total ? (Number(x.amount) / total) * 100 : 0); const a = segments[0] || 0; const b = (segments[1] || 0) + a;
  return <Stack direction={{ xs: "column", sm: "row" }} spacing={3} sx={{ alignItems: "center" }}><Box sx={{ width: 150, height: 150, borderRadius: "50%", background: `conic-gradient(#1976d2 0 ${a}%, #9c27b0 ${a}% ${b}%, #2e7d32 ${b}% 100%)`, position: "relative" }}><Box sx={{ position: "absolute", inset: 28, bgcolor: "background.paper", borderRadius: "50%", display: "grid", placeItems: "center" }}><Typography sx={{ fontWeight: 800 }}>{compactMoney(total)}</Typography></Box></Box><Stack spacing={1} sx={{ flex: 1 }}>{values.map((x) => <Stack direction="row" sx={{ justifyContent: "space-between" }} key={x.method}><Typography>{x.method_name}</Typography><Typography sx={{ fontWeight: 700 }}>{money(x.amount)}</Typography></Stack>)}</Stack></Stack>;
}

export default function Reports() {
  const { activeStore, stores, activeRole } = useStore();
  const [storeId, setStoreId] = useState<number | "all">(activeStore?.id ?? "all");
  const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [summary, setSummary] = useState<Summary | null>(null); const [daily, setDaily] = useState<Daily[]>([]); const [monthly, setMonthly] = useState<Monthly[]>([]); const [methods, setMethods] = useState<PaymentMethod[]>([]); const [top, setTop] = useState<TopProduct[]>([]); const [financial, setFinancial] = useState<Financial | null>(null); const [cancellations, setCancellations] = useState<Cancellation[]>([]); const [cash, setCash] = useState<CashRecon[]>([]);
  const isManager = activeRole === "manager";
  const params = useMemo(() => ({ store: storeId === "all" ? undefined : storeId, start_date: start, end_date: end }), [storeId, start, end]);
  const load = async () => { setLoading(true); setError(""); try { const [s,d,m,pm,tp,fr,cr] = await Promise.all([summaryReport(params), dailySales(params), monthlySales(params), paymentMethods(params), topProducts(params), financialReport(params), cancellationsReport(params)]); setSummary(s); setDaily(d); setMonthly(m); setMethods(pm); setTop(tp); setFinancial(fr); setCancellations(cr); if (activeRole === "manager" || activeRole === "cashier") setCash(await cashReconciliation(params)); else setCash([]); } catch (e) { setError(errorMessage(e)); } finally { setLoading(false); } };
  useEffect(() => { if (activeStore) setStoreId(activeStore.id); }, [activeStore?.id]);
  useEffect(() => { if (activeStore) void load(); }, [activeStore?.id, activeRole]);
  const setRange = (kind: "today" | "month" | "all") => { if (kind === "all") { setStart(""); setEnd(""); return; } const now = new Date(); setEnd(iso(now)); if (kind === "today") setStart(iso(now)); else setStart(iso(new Date(now.getFullYear(), now.getMonth(), 1))); };
  if (!activeStore) return <Alert severity="warning">ابتدا یک فروشگاه انتخاب کنید.</Alert>;
  const gross = Number(summary?.gross_profit || 0); const net = Number(financial?.balance || 0);
  return <Box dir="rtl"><Stack direction={{ xs: "column", md: "row" }} sx={{ mb: 2, justifyContent: "space-between", gap: 1 }}><Box><Typography variant="h5" sx={{ fontWeight: 800 }}>داشبورد حرفه‌ای گزارش‌ها</Typography><Typography color="text.secondary">تصویر مدیریتی فروش، سود، پرداخت و صندوق</Typography></Box><Button variant="contained" startIcon={<RefreshIcon />} onClick={() => void load()} disabled={loading}>به‌روزرسانی</Button></Stack>
    <Card sx={{ mb: 2 }}><CardContent><Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ alignItems: { md: "center" } }}><FormControl size="small" sx={{ minWidth: 220 }}><InputLabel>فروشگاه</InputLabel><Select label="فروشگاه" value={storeId} onChange={e => setStoreId(e.target.value === "all" ? "all" : Number(e.target.value))}>{isManager && <MenuItem value="all">همه فروشگاه‌ها</MenuItem>}{stores.map(s => <MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</Select></FormControl><Stack direction="row" spacing={1}><Button size="small" variant="outlined" onClick={() => setRange("today")}>امروز</Button><Button size="small" variant="outlined" onClick={() => setRange("month")}>این ماه</Button><Button size="small" variant="outlined" onClick={() => setRange("all")}>همه</Button></Stack><Stack direction="row" spacing={1} sx={{ flex: 1 }}><Box component="input" type="date" value={start} onChange={(e: any) => setStart(e.target.value)} style={{ padding: 10, border: "1px solid #ccc", borderRadius: 6, width: "100%" }} /><Box component="input" type="date" value={end} onChange={(e: any) => setEnd(e.target.value)} style={{ padding: 10, border: "1px solid #ccc", borderRadius: 6, width: "100%" }} /></Stack><Button variant="outlined" onClick={() => void load()} disabled={loading}>اعمال فیلتر</Button></Stack></CardContent></Card>
    {error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError("")}>{error}</Alert>}
    {loading ? <Box sx={{ display: "grid", placeItems: "center", minHeight: 360 }}><CircularProgress /></Box> : <Stack spacing={2}>
      <Stack direction={{ xs: "column", md: "row" }} spacing={2}><Kpi title="فروش خالص" value={`${money(summary?.sales || 0)} ریال`} icon={<TrendingUpIcon />} caption={`${summary?.order_count || 0} فاکتور`} /><Kpi title="سود ناخالص" value={`${money(gross)} ریال`} icon={<AccountBalanceWalletIcon />} /><Kpi title="هزینه‌ها" value={`${money(financial?.expenses || 0)} ریال`} icon={<PaymentsIcon />} /><Kpi title="لغوها" value={`${summary?.cancelled_count || 0}`} icon={<CancelIcon />} caption={`${money(summary?.cancelled_sales || 0)} ریال`} /></Stack>
      <Stack direction={{ xs: "column", lg: "row" }} spacing={2}><Card sx={{ flex: 2 }}><CardContent><Typography variant="h6" sx={{ fontWeight: 700 }}>روند فروش روزانه</Typography><Divider sx={{ my: 1 }} /><TrendChart rows={daily} /></CardContent></Card><Card sx={{ flex: 1 }}><CardContent><Typography variant="h6" sx={{ fontWeight: 700,  mb: 2 }}>ترکیب پرداخت</Typography><PaymentMix rows={methods} summary={summary} /></CardContent></Card></Stack>
      <Stack direction={{ xs: "column", lg: "row" }} spacing={2}><Card sx={{ flex: 1 }}><CardContent><Typography variant="h6" sx={{ fontWeight: 700 }}>محصولات پرفروش</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>کالا</TableCell><TableCell>تعداد</TableCell><TableCell>فروش</TableCell></TableRow></TableHead><TableBody>{top.slice(0, 10).map(x => <TableRow key={x.product_id}><TableCell>{x.product_name}</TableCell><TableCell>{money(x.total_quantity)}</TableCell><TableCell>{money(x.total_sales)}</TableCell></TableRow>)}{!top.length && <TableRow><TableCell colSpan={3} align="center">داده‌ای وجود ندارد.</TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card><Card sx={{ flex: 1 }}><CardContent><Typography variant="h6" sx={{ fontWeight: 700 }}>خلاصه مالی</Typography><Stack spacing={2} sx={{ mt: 2 }}><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography>فروش</Typography><Typography sx={{ fontWeight: 700 }}>{money(financial?.sales || 0)}</Typography></Stack><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography>هزینه</Typography><Typography sx={{ fontWeight: 700 }}>{money(financial?.expenses || 0)}</Typography></Stack><Divider /><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography sx={{ fontWeight: 700 }}>خالص</Typography><Typography sx={{ fontWeight: 800 }}>{money(net)}</Typography></Stack></Stack><Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 2 }}>بهای تمام‌شده کالا در سود ناخالص محاسبه شده است.</Typography></CardContent></Card></Stack>
      <Card><CardContent><Typography variant="h6" sx={{ fontWeight: 700 }}>فروش ماهانه</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>ماه</TableCell><TableCell>فاکتور</TableCell><TableCell>فروش</TableCell></TableRow></TableHead><TableBody>{monthly.slice(0, 12).map(x => <TableRow key={x.month}><TableCell>{x.month}</TableCell><TableCell>{x.order_count}</TableCell><TableCell>{money(x.total_sales)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
      {(activeRole === "manager" || activeRole === "cashier") && <Card><CardContent><Typography variant="h6" sx={{ fontWeight: 700 }}>کنترل مغایرت صندوق</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>صندوق</TableCell><TableCell>مانده</TableCell><TableCell>دفتر</TableCell><TableCell>اختلاف</TableCell><TableCell>وضعیت</TableCell></TableRow></TableHead><TableBody>{cash.map(x => <TableRow key={x.id}><TableCell>{x.name}</TableCell><TableCell>{money(x.balance)}</TableCell><TableCell>{money(x.ledger_balance)}</TableCell><TableCell>{money(x.difference)}</TableCell><TableCell><Chip size="small" label={x.is_balanced ? "تراز" : "مغایرت"} color={x.is_balanced ? "success" : "error"} /></TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>}
      <Card><CardContent><Typography variant="h6" sx={{ fontWeight: 700 }}>تاریخچه لغو فاکتورها</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>فاکتور</TableCell><TableCell>مبلغ</TableCell><TableCell>لغوکننده</TableCell><TableCell>علت</TableCell><TableCell>زمان</TableCell></TableRow></TableHead><TableBody>{cancellations.slice(0, 20).map(x => <TableRow key={x.order_id}><TableCell>{x.order_id}</TableCell><TableCell>{money(x.amount)}</TableCell><TableCell>{x.cancelled_by || "-"}</TableCell><TableCell>{x.reason || "-"}</TableCell><TableCell>{x.cancelled_at}</TableCell></TableRow>)}{!cancellations.length && <TableRow><TableCell colSpan={5} align="center">لغوی ثبت نشده است.</TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card>
    </Stack>}
  </Box>;
}
