import {useEffect,useMemo,useState} from "react";
import {Alert,Box,Button,Card,CardContent,Chip,CircularProgress,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography} from "@mui/material";
import {useStore} from "../contexts/StoreContext";
import {cancellationsReport,cashReconciliation,dailySales,financialReport,monthlySales,paymentMethods,profitReport,topProducts,type Cancellation,type CashRecon,type Daily,type Financial,type PaymentMethod,type Profit,type TopProduct} from "../services/reportService";
const money=(v:string|number)=>Number(v||0).toLocaleString("fa-IR");
export default function Reports(){
 const {activeStore,activeRole}=useStore(); const [start,setStart]=useState("");const [end,setEnd]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 const [daily,setDaily]=useState<Daily[]>([]),[monthly,setMonthly]=useState<{month:string;order_count:number;total_sales:string}[]>([]),[methods,setMethods]=useState<PaymentMethod[]>([]),[top,setTop]=useState<TopProduct[]>([]),[profit,setProfit]=useState<Profit|null>(null),[financial,setFinancial]=useState<Financial|null>(null),[cancellations,setCancellations]=useState<Cancellation[]>([]),[cash,setCash]=useState<CashRecon[]>([]);
 const params=useMemo(()=>({store:activeStore?.id,start_date:start,end_date:end}),[activeStore?.id,start,end]);
 const load=async()=>{if(!activeStore)return;setLoading(true);setError("");try{const [d,m,pm,tp,pr,fr,cr]=await Promise.all([dailySales(params),monthlySales(params),paymentMethods(params),topProducts(params),profitReport(params),financialReport(params),cancellationsReport(params)]);setDaily(d);setMonthly(m);setMethods(pm);setTop(tp);setProfit(pr);setFinancial(fr);setCancellations(cr);if(activeRole==="manager"||activeRole==="cashier")setCash(await cashReconciliation(params));else setCash([]);}catch(e:any){setError(e?.response?.data?.detail||"دریافت گزارش‌ها انجام نشد.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[activeStore?.id,activeRole]); if(!activeStore)return <Alert severity="warning">ابتدا یک فروشگاه انتخاب کنید.</Alert>;
 return <Box dir="rtl"><Stack direction={{xs:"column",md:"row"}} sx={{mb:2,justifyContent:"space-between"}}><Typography variant="h5">گزارش‌های فروش و مالی</Typography><Button variant="contained" onClick={()=>void load()} disabled={loading}>به‌روزرسانی</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
 <Card sx={{mb:2}}><CardContent><Stack direction={{xs:"column",sm:"row"}} spacing={2}><TextField type="date" label="از تاریخ" slotProps={{inputLabel:{shrink:true}}} value={start} onChange={e=>setStart(e.target.value)}/><TextField type="date" label="تا تاریخ" slotProps={{inputLabel:{shrink:true}}} value={end} onChange={e=>setEnd(e.target.value)}/><Button variant="outlined" onClick={()=>{setStart("");setEnd("")}}>همه</Button></Stack></CardContent></Card>
 {loading?<Box sx={{display:"grid",placeItems:"center",minHeight:240}}><CircularProgress/></Box>:<Stack spacing={2}>
 {profit&&<Card><CardContent><Typography variant="h6">خلاصه سود</Typography><Stack direction={{xs:"column",sm:"row"}} spacing={4} sx={{mt:1}}><Typography>فروش خالص: <strong>{money(profit.total_sales)}</strong></Typography><Typography>بهای تمام‌شده: <strong>{money(profit.total_cost)}</strong></Typography><Typography>سود ناخالص: <strong>{money(profit.total_profit)}</strong></Typography></Stack></CardContent></Card>}
 {financial&&<Card><CardContent><Typography variant="h6">خلاصه مالی</Typography><Stack direction={{xs:"column",sm:"row"}} spacing={4} sx={{mt:1}}><Typography>فروش: <strong>{money(financial.sales)}</strong></Typography><Typography>هزینه: <strong>{money(financial.expenses)}</strong></Typography><Typography>خالص: <strong>{money(financial.balance)}</strong></Typography></Stack></CardContent></Card>}
 <Card><CardContent><Typography variant="h6">فروش بر اساس روش پرداخت</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>روش</TableCell><TableCell>تعداد</TableCell><TableCell>مبلغ</TableCell></TableRow></TableHead><TableBody>{methods.map(x=><TableRow key={x.method}><TableCell>{x.method_name}</TableCell><TableCell>{x.transaction_count}</TableCell><TableCell>{money(x.amount)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 <Card><CardContent><Typography variant="h6">فروش ماهانه</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>ماه</TableCell><TableCell>تعداد فروش</TableCell><TableCell>مبلغ</TableCell></TableRow></TableHead><TableBody>{monthly.map(x=><TableRow key={x.month}><TableCell>{x.month}</TableCell><TableCell>{x.order_count}</TableCell><TableCell>{money(x.total_sales)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card><Card><CardContent><Typography variant="h6">فروش روزانه</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>روز</TableCell><TableCell>تعداد فروش</TableCell><TableCell>مبلغ</TableCell></TableRow></TableHead><TableBody>{daily.map(x=><TableRow key={x.day}><TableCell>{x.day}</TableCell><TableCell>{x.order_count}</TableCell><TableCell>{money(x.total_sales)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 <Card><CardContent><Typography variant="h6">محصولات پرفروش</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>کالا</TableCell><TableCell>تعداد</TableCell><TableCell>فروش</TableCell></TableRow></TableHead><TableBody>{top.map(x=><TableRow key={x.product_id}><TableCell>{x.product_name}</TableCell><TableCell>{x.total_quantity}</TableCell><TableCell>{money(x.total_sales)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 {(activeRole==="manager"||activeRole==="cashier")&&<Card><CardContent><Typography variant="h6">کنترل مغایرت صندوق</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>صندوق</TableCell><TableCell>مانده</TableCell><TableCell>دفتر</TableCell><TableCell>مغایرت</TableCell><TableCell>وضعیت</TableCell></TableRow></TableHead><TableBody>{cash.map(x=><TableRow key={x.id}><TableCell>{x.name}</TableCell><TableCell>{money(x.balance)}</TableCell><TableCell>{money(x.ledger_balance)}</TableCell><TableCell>{money(x.difference)}</TableCell><TableCell><Chip size="small" label={x.is_balanced?"تراز است":"دارای مغایرت"} color={x.is_balanced?"success":"error"}/></TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>}
 <Card><CardContent><Typography variant="h6">تاریخچه لغو فروش</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>فاکتور</TableCell><TableCell>مبلغ</TableCell><TableCell>لغوکننده</TableCell><TableCell>علت</TableCell><TableCell>زمان</TableCell></TableRow></TableHead><TableBody>{cancellations.map(x=><TableRow key={x.order_id}><TableCell>{x.order_id}</TableCell><TableCell>{money(x.amount)}</TableCell><TableCell>{x.cancelled_by||"-"}</TableCell><TableCell>{x.reason||"-"}</TableCell><TableCell>{x.cancelled_at}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 </Stack>}</Box>;
}
