import { useEffect,useState } from "react";
import { Alert,Autocomplete,Box,Button,Card,CardContent,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,MenuItem,Paper,Select,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography } from "@mui/material";
import DeleteIcon from "@mui/icons-material/Delete"; import CancelIcon from "@mui/icons-material/Cancel"; import AddShoppingCartIcon from "@mui/icons-material/AddShoppingCart"; import PaymentIcon from "@mui/icons-material/Payment"; import ReceiptLongIcon from "@mui/icons-material/ReceiptLong";
import { useStore } from "../../contexts/StoreContext"; import { listProducts,type Product } from "../../services/productService"; import { listCustomers,getCustomerBalance,type Customer,type CustomerBalance } from "../../services/customerService"; import { listCashBoxes,type CashBox } from "../../services/cashboxService"; import { addCartItem,checkout,createCart,deleteCartItem,listCarts,listOrders,updateCartCustomer,changeOrderStatus,downloadInvoicePdf,downloadThermalReceiptPdf,type Cart,type CheckoutPayment,type Order,type PaymentMethod } from "../../services/salesService";
const money=(v:string|number)=>Number(v||0).toLocaleString("fa-IR");
const apiErrorMessage=(e:any)=>{
 const data=e?.response?.data;
 if(typeof data?.detail==="string") return data.detail;
 if(typeof data?.message==="string") return data.message;
 if(typeof data==="string") return data;
 if(data&&typeof data==="object"){
  for(const value of Object.values(data)){
   if(typeof value==="string") return value;
   if(Array.isArray(value)&&typeof value[0]==="string") return value[0];
  }
 }
 return "عملیات انجام نشد.";
};
export default function Sales(){
 const {activeStore,activeRole}=useStore(); const [products,setProducts]=useState<Product[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [cashboxes,setCashboxes]=useState<CashBox[]>([]); const [cart,setCart]=useState<Cart|null>(null); const [orders,setOrders]=useState<Order[]>([]); const [product,setProduct]=useState<Product|null>(null); const [barcode,setBarcode]=useState(""); const [quantity,setQuantity]=useState("1"); const [discount,setDiscount]=useState("0"); const [customerId,setCustomerId]=useState<number|null>(null); const [customerBalance,setCustomerBalance]=useState<CustomerBalance|null>(null); const [method,setMethod]=useState<PaymentMethod>(activeRole==="seller"?"credit":"cash"); const [payments,setPayments]=useState<CheckoutPayment[]>([]); const [cashboxId,setCashboxId]=useState<number|"">(""); const [cashAmount,setCashAmount]=useState(""); const [cashReceived,setCashReceived]=useState(""); const [cashReceivedEdited,setCashReceivedEdited]=useState(false); const [cardAmount,setCardAmount]=useState(""); const [creditAmount,setCreditAmount]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [detailOrder,setDetailOrder]=useState<Order|null>(null); const [printing,setPrinting]=useState(false);
 const refresh=async(id:number)=>{
  const needsCashbox=activeRole==="manager"||activeRole==="cashier";
  const results=await Promise.allSettled([listProducts(id),listCustomers(id),needsCashbox?listCashBoxes(id):Promise.resolve([] as CashBox[]),listOrders(id),listCarts(id)]);
  const [p,c,b,o,carts]=results;
  const failures=results.filter(x=>x.status==="rejected") as PromiseRejectedResult[];
  if(failures.length){
    const first=failures[0].reason as any;
    const detail=first?.response?.data?.detail || first?.response?.data?.message;
    throw new Error(detail || `دریافت اطلاعات فروشگاه با ${failures.length} خطا مواجه شد.`);
  }
  const productsData=(p as PromiseFulfilledResult<Product[]>).value;
  const customersData=(c as PromiseFulfilledResult<Customer[]>).value;
  const cashboxesData=(b as PromiseFulfilledResult<CashBox[]>).value;
  const ordersData=(o as PromiseFulfilledResult<Order[]>).value;
  const cartsData=(carts as PromiseFulfilledResult<Cart[]>).value;
  setProducts(productsData.filter(x=>x.is_active!==false));setCustomers(customersData);setCashboxes(cashboxesData);setOrders(ordersData);setCart(cartsData[0]??null);if(cartsData[0]?.customer){setCustomerId(cartsData[0].customer);}else{setCustomerId(null);setCustomerBalance(null);}setPayments([]);setCashAmount("");setCashReceived("");setCashReceivedEdited(false);setCardAmount("");setCreditAmount("");setProduct(null);setBarcode("");setQuantity("1");setDiscount("0");if(cashboxesData.length)setCashboxId(cashboxesData[0].id);else setCashboxId("");
 };
 useEffect(()=>{if(!activeStore)return;setLoading(true);setError("");setCart(null);setPayments([]);setCashAmount("");setCashReceived("");setCashReceivedEdited(false);setCardAmount("");setCreditAmount("");setCustomerId(null);setCustomerBalance(null);setProduct(null);setBarcode("");void refresh(activeStore.id).catch(e=>{console.error(e);setError(e?.message || "خطا در دریافت اطلاعات فروشگاه");}).finally(()=>setLoading(false));},[activeStore,activeRole]);
 const total=Number(cart?.total_price||0),paid=payments.reduce((s,p)=>s+Number(p.amount||0),0),remaining=total-paid,selectedCustomer=customers.find(c=>c.id===customerId)||null;
 useEffect(()=>{if(remaining<=0)return; if(method==="cash"){if(!cashReceivedEdited)setCashReceived(remaining.toFixed(2)); if(!cashAmount)setCashAmount(remaining.toFixed(2));} if(method==="card"&&!cardAmount)setCardAmount(remaining.toFixed(2)); if(method==="credit"&&!creditAmount)setCreditAmount(remaining.toFixed(2));},[method,remaining,cashReceivedEdited,cashAmount,cardAmount,creditAmount]); const receivedCash=Number(cashReceived||0); const selectedCashAmount=Number(cashAmount||0); const change=method==="cash"&&receivedCash>=selectedCashAmount&&selectedCashAmount>0?receivedCash-selectedCashAmount:0;
 const ensureCart=async()=>{if(cart)return cart;if(!activeStore)throw new Error("store");const c=await createCart(activeStore.id,customerId);setCart(c);return c;};
 const add=async()=>{if(!product&&!barcode.trim()){setError("یک کالا انتخاب کنید یا بارکد را وارد کنید.");return;}try{setSaving(true);setError("");const c=await ensureCart();const item=await addCartItem(c.id,{...(product?{product:product.id}:{barcode:barcode.trim()}),quantity,discount_percent:discount});const items=c.items.some(x=>x.id===item.id)?c.items.map(x=>x.id===item.id?item:x):[...c.items,item];setCart({...c,items,total_before_discount:String(items.reduce((s,x)=>s+Number(x.total_price_before_discount),0)),total_discount:String(items.reduce((s,x)=>s+Number(x.total_discount_amount),0)),total_price:String(items.reduce((s,x)=>s+Number(x.total_price),0))});setProduct(null);setBarcode("");setQuantity("1");setDiscount("0");setPayments([]);}catch(e:any){console.error(e);setError(apiErrorMessage(e)==="عملیات انجام نشد."?"افزودن کالا به سبد انجام نشد.":apiErrorMessage(e));}finally{setSaving(false);}};
 const changeCustomer=async(id:number|null)=>{setCustomerId(id);setCustomerBalance(null);if(id){try{setCustomerBalance(await getCustomerBalance(id));}catch{setError("دریافت مانده حساب مشتری انجام نشد.");}}if(!cart)return;try{setCart(await updateCartCustomer(cart.id,id));}catch{setError("تغییر مشتری انجام نشد.");}};
 const remove=async(id:number)=>{if(!cart)return;try{await deleteCartItem(cart.id,id);const items=cart.items.filter(x=>x.id!==id);setCart({...cart,items,total_before_discount:String(items.reduce((s,x)=>s+Number(x.total_price_before_discount),0)),total_discount:String(items.reduce((s,x)=>s+Number(x.total_discount_amount),0)),total_price:String(items.reduce((s,x)=>s+Number(x.total_price),0))});setPayments([]);}catch{setError("حذف کالا انجام نشد.");}};
 const addPayment=()=>{if(remaining<=0)return;if(method==="credit"&&!customerId){setError("برای فروش اعتباری ابتدا مشتری را انتخاب کنید.");return;}let amount=remaining;if(method==="card"){amount=Number(cardAmount||0);if(!Number.isFinite(amount)||amount<=0||amount>remaining){setError(`مبلغ کارتخوان باید بین 1 و ${money(remaining)} باشد.`);return;}}if(method==="credit"){amount=Number(creditAmount||0);if(!Number.isFinite(amount)||amount<=0||amount>remaining){setError(`مبلغ اعتباری باید بین 1 و ${money(remaining)} باشد.`);return;}}if(method==="cash"){amount=Number(cashAmount||0);const received=Number(cashReceived||0);if(!Number.isFinite(amount)||amount<=0||amount>remaining){setError(`مبلغ پرداخت نقدی باید بین 1 و ${money(remaining)} باشد.`);return;}if(!Number.isFinite(received)||received<amount){setError(`مبلغ دریافتی باید حداقل ${money(amount)} باشد.`);return;}}setError("");setPayments(p=>[...p,{method,amount:amount.toFixed(2),cashbox_id:method==="credit"?null:Number(cashboxId)}]);setCashAmount("");setCashReceived("");setCashReceivedEdited(false);setCardAmount("");setCreditAmount("");};
 const showOrderDetail=(order:Order)=>setDetailOrder(order);
 const printThermalReceipt=async(order:Order)=>{try{setPrinting(true);setError("");const blob=await downloadThermalReceiptPdf(order.id);const url=URL.createObjectURL(blob);const win=window.open(url,"_blank","noopener,noreferrer");if(!win){const a=document.createElement("a");a.href=url;a.download=`receipt-thermal-${order.id}.pdf`;a.click();}else{win.addEventListener("load",()=>win.print(),{once:true});}window.setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e:any){console.error(e);setError(apiErrorMessage(e));}finally{setPrinting(false);}};
 const printInvoice=async(order:Order)=>{try{setPrinting(true);setError("");const blob=await downloadInvoicePdf(order.id);const url=URL.createObjectURL(blob);const win=window.open(url,"_blank","noopener,noreferrer");if(!win){const a=document.createElement("a");a.href=url;a.download=`invoice-${order.id}.pdf`;a.click();}else{win.addEventListener("load",()=>win.print(),{once:true});}window.setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e:any){console.error(e);setError(apiErrorMessage(e));}finally{setPrinting(false);}};
 const cancelOrder=async(order:Order)=>{if(order.status==="cancelled")return;if(!window.confirm(`آیا از لغو فروش شماره ${order.id} به مبلغ ${money(order.total_price)} اطمینان دارید؟\nموجودی، صندوق و حساب مشتری در صورت لزوم اصلاح می‌شوند.`))return;try{setSaving(true);setError("");setSuccess("");const reason=window.prompt("علت لغو فروش را وارد کنید (اختیاری):","")??"";await changeOrderStatus(order.id,"cancelled",reason);setSuccess(`فروش شماره ${order.id} با موفقیت لغو شد و اصلاحات مالی/موجودی انجام شد.`);if(activeStore)await refresh(activeStore.id);}catch(e:any){console.error(e);setError(apiErrorMessage(e));}finally{setSaving(false);}};
 const doCheckout=async()=>{if(!cart||!cart.items.length){setError("سبد فروش خالی است.");return;}if(!payments.length||Math.abs(remaining)>0.009){setError("مجموع پرداخت‌ها باید دقیقاً برابر مبلغ سفارش باشد.");return;}if(payments.some(p=>(p.method==="cash"||p.method==="card")&&!p.cashbox_id)){setError("برای پرداخت نقدی یا کارتخوان صندوق الزامی است.");return;}if(payments.some(p=>p.method==="credit")&&!customerId){setError("فروش حسابی بدون مشتری مجاز نیست.");return;}try{setSaving(true);setError("");const r=await checkout(cart.id,payments);setSuccess(`فروش شماره ${r.id} با موفقیت ثبت شد.`);setCart(null);setPayments([]);setCustomerId(null);setCustomerBalance(null);if(activeStore)await refresh(activeStore.id);}catch(e){console.error(e);setError("ثبت فروش انجام نشد. اطلاعات پرداخت و موجودی را بررسی کنید.");}finally{setSaving(false);}};
 if(!activeStore)return <Alert severity="warning">ابتدا یک فروشگاه انتخاب کنید.</Alert>; if(loading)return <Box sx={{display:"grid",placeItems:"center",minHeight:300}}><CircularProgress/></Box>;
 return <Box dir="rtl"><Typography variant="h5" sx={{mb:2}}>ثبت فروش</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{success&&<Alert severity="success" sx={{mb:2}}>{success}</Alert>}<Stack spacing={2}>
 <Card><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{alignItems:"center"}}><Autocomplete sx={{minWidth:320,flex:1}} options={products} value={product} getOptionLabel={x=>`${x.name}${x.barcode?` — ${x.barcode}`:""}`} onChange={(_,v)=>setProduct(v)} renderOption={(props,x)=><li {...props} key={x.id}><Box sx={{width:"100%"}}><Typography>{x.name}</Typography><Typography variant="caption" sx={{display:"block"}}>موجودی: <strong>{money(x.inventory_quantity ?? 0)}</strong>{x.unit?` ${x.unit}`:""}{x.barcode?` — ${x.barcode}`:""}</Typography></Box></li>} renderInput={p=><TextField {...p} label="کالا" helperText={product?`موجودی این فروشگاه: ${money(product.inventory_quantity ?? 0)} ${product.unit||"واحد"}`:undefined}/>}/><TextField label="بارکد" value={barcode} onChange={e=>setBarcode(e.target.value)}/><TextField label="تعداد" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} sx={{width:110}}/><TextField label="تخفیف %" type="number" value={discount} onChange={e=>setDiscount(e.target.value)} sx={{width:110}}/><Button variant="contained" startIcon={<AddShoppingCartIcon/>} onClick={()=>void add()} disabled={saving}>افزودن</Button></Stack></CardContent></Card>
 <Card><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{alignItems:"center"}}><Autocomplete sx={{minWidth:300,flex:1}} options={customers} value={selectedCustomer} getOptionLabel={x=>`${x.first_name} ${x.last_name} — ${x.mobile}`} onChange={(_,v)=>void changeCustomer(v?.id??null)} renderInput={p=><TextField {...p} label="مشتری"/>}/><Typography>مبلغ نهایی: <strong>{money(total)}</strong></Typography>{selectedCustomer&&customerBalance&&<Typography>مانده حساب: <strong>{money(customerBalance.balance)}</strong></Typography>}</Stack></CardContent></Card>
 <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>کالا</TableCell><TableCell>تعداد</TableCell><TableCell>قیمت</TableCell><TableCell>تخفیف</TableCell><TableCell>جمع</TableCell><TableCell/></TableRow></TableHead><TableBody>{(cart?.items||[]).map(i=><TableRow key={i.id}><TableCell>{i.product_name}</TableCell><TableCell>{i.quantity}</TableCell><TableCell>{money(i.unit_price)}</TableCell><TableCell>{i.discount_percent}%</TableCell><TableCell>{money(i.total_price)}</TableCell><TableCell><IconButton onClick={()=>void remove(i.id)}><DeleteIcon/></IconButton></TableCell></TableRow>)}{(!cart||!cart.items.length)&&<TableRow><TableCell colSpan={6} align="center">سبد فروش خالی است.</TableCell></TableRow>}</TableBody></Table></TableContainer>
 <Card><CardContent><Typography variant="h6" sx={{mb:2}}>پرداخت</Typography><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{alignItems:"center"}}><Select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}>{(activeRole==="seller"?["credit"]:["cash","card","credit"]).map(m=><MenuItem key={m} value={m}>{m==="cash"?"نقدی":m==="card"?"کارتخوان":"حسابی"}</MenuItem>)}</Select>{(method==="cash"||method==="card")&&<Select value={cashboxId} onChange={e=>setCashboxId(Number(e.target.value))} displayEmpty><MenuItem value="" disabled>انتخاب صندوق</MenuItem>{cashboxes.map(b=><MenuItem key={b.id} value={b.id}>{b.name} — {money(b.balance)}</MenuItem>)}</Select>}<Typography>باقی‌مانده: <strong>{money(Math.max(remaining,0))}</strong></Typography>{method==="cash"&&<><TextField label="مبلغ پرداخت نقدی" type="number" value={cashAmount} onChange={e=>setCashAmount(e.target.value)} sx={{width:170}}/><TextField label="مبلغ دریافتی مشتری" type="number" value={cashReceived} onChange={e=>{setCashReceived(e.target.value);setCashReceivedEdited(true);}} sx={{width:180}}/><Typography>باقی پول: <strong>{money(change)}</strong></Typography></>}{method==="card"&&<TextField label="مبلغ کارتخوان" type="number" value={cardAmount} onChange={e=>setCardAmount(e.target.value)} sx={{width:170}} helperText="مبلغ تراکنش کارتخوان" />}{method==="credit"&&<TextField label="مبلغ اعتباری" type="number" value={creditAmount} onChange={e=>setCreditAmount(e.target.value)} sx={{width:170}} helperText="مبلغی که به حساب مشتری منظور می‌شود" />}<Button variant="outlined" startIcon={<PaymentIcon/>} onClick={addPayment} disabled={!cart||remaining<=0}>افزودن پرداخت</Button><Button variant="contained" color="success" startIcon={<ReceiptLongIcon/>} onClick={()=>void doCheckout()} disabled={saving||!cart||!cart.items.length||!payments.length||Math.abs(remaining)>0.009}>ثبت نهایی</Button></Stack>{payments.map((p,i)=><Paper key={i} variant="outlined" sx={{p:1,mt:1,display:"flex",justifyContent:"space-between"}}><span>{p.method==="cash"?"نقدی":p.method==="card"?"کارتخوان":"حسابی"} — {money(p.amount)}</span><Button size="small" color="error" onClick={()=>setPayments(x=>x.filter((_,j)=>j!==i))}>حذف</Button></Paper>)}</CardContent></Card>
 <Typography variant="h6">آخرین فروش‌ها</Typography><TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>شماره</TableCell><TableCell>مشتری</TableCell><TableCell>مبلغ</TableCell><TableCell>وضعیت</TableCell><TableCell>تاریخ</TableCell><TableCell>عملیات</TableCell></TableRow></TableHead><TableBody>{orders.slice(0,10).map(o=><TableRow key={o.id}><TableCell>{o.id}</TableCell><TableCell>{o.customer_name||"مشتری نقدی"}</TableCell><TableCell>{money(o.total_price)}</TableCell><TableCell>{o.status==="paid"?"پرداخت شده":o.status==="cancelled"?"لغو شده":o.status==="confirmed"?"تأیید شده":"در انتظار"}</TableCell><TableCell>{o.created_at}</TableCell><TableCell><Stack direction="row" spacing={1}><Button size="small" variant="outlined" onClick={()=>showOrderDetail(o)}>جزئیات</Button><Button size="small" variant="outlined" onClick={()=>void printInvoice(o)} disabled={printing}>چاپ فاکتور</Button><Button size="small" variant="outlined" onClick={()=>void printThermalReceipt(o)} disabled={printing}>چاپ حرارتی</Button>{(activeRole==="manager"||activeRole==="cashier")&&o.status!=="cancelled"&&<Button size="small" color="error" variant="outlined" startIcon={<CancelIcon/>} onClick={()=>void cancelOrder(o)} disabled={saving}>لغو فروش</Button>}</Stack></TableCell></TableRow>)}</TableBody></Table></TableContainer>
 <Dialog open={Boolean(detailOrder)} onClose={()=>setDetailOrder(null)} fullWidth maxWidth="md"><DialogTitle>جزئیات فاکتور {detailOrder?.id??""}</DialogTitle><DialogContent dividers>{detailOrder&&<Stack spacing={2} dir="rtl"><Stack direction={{xs:"column",md:"row"}} spacing={3}><Typography>فروشگاه: <strong>{activeStore?.name}</strong></Typography><Typography>مشتری: <strong>{detailOrder.customer_name||"مشتری متفرقه"}</strong></Typography><Typography>وضعیت: <strong>{detailOrder.status==="paid"?"پرداخت شده":detailOrder.status==="cancelled"?"لغو شده":detailOrder.status==="confirmed"?"تأیید شده":"در انتظار"}</strong></Typography></Stack><Table size="small"><TableHead><TableRow><TableCell>کالا</TableCell><TableCell>تعداد</TableCell><TableCell>قیمت واحد</TableCell><TableCell>تخفیف</TableCell><TableCell>جمع</TableCell></TableRow></TableHead><TableBody>{detailOrder.items.map(i=><TableRow key={i.id}><TableCell>{i.product_name}</TableCell><TableCell>{i.quantity}</TableCell><TableCell>{money(i.unit_price)}</TableCell><TableCell>{i.discount_percent}%</TableCell><TableCell>{money(i.total_price)}</TableCell></TableRow>)}</TableBody></Table><Stack spacing={0.5}><Typography>قبل از تخفیف: <strong>{money(detailOrder.total_before_discount)}</strong></Typography><Typography>تخفیف: <strong>{money(detailOrder.total_discount)}</strong></Typography><Typography variant="h6">مبلغ نهایی: <strong>{money(detailOrder.total_price)}</strong></Typography></Stack><Typography variant="subtitle1">روش‌های پرداخت</Typography>{detailOrder.status==="cancelled"&&detailOrder.cancellation&&<Alert severity="error">لغوکننده: {detailOrder.cancellation.cancelled_by_username} — زمان: {detailOrder.cancellation.cancelled_at} — علت: {detailOrder.cancellation.reason||"ثبت نشده"}</Alert>}{detailOrder.payments.map(p=><Typography key={p.id}>{p.method==="cash"?"نقدی":p.method==="card"?"کارتخوان":"حسابی"}: <strong>{money(p.amount)}</strong></Typography>)}</Stack>}</DialogContent><DialogActions><Button onClick={()=>setDetailOrder(null)}>بستن</Button>{detailOrder&&<><Button variant="contained" onClick={()=>void printInvoice(detailOrder)} disabled={printing}>چاپ فاکتور</Button><Button variant="outlined" onClick={()=>void printThermalReceipt(detailOrder)} disabled={printing}>چاپ حرارتی</Button></>}</DialogActions></Dialog>
 </Stack></Box>;
}
