import { useEffect,useState } from "react";
import { Alert,Autocomplete,Box,Button,Card,CardContent,CircularProgress,IconButton,MenuItem,Paper,Select,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography } from "@mui/material";
import DeleteIcon from "@mui/icons-material/Delete"; import AddShoppingCartIcon from "@mui/icons-material/AddShoppingCart"; import PaymentIcon from "@mui/icons-material/Payment"; import ReceiptLongIcon from "@mui/icons-material/ReceiptLong";
import { useStore } from "../../contexts/StoreContext"; import { listProducts,type Product } from "../../services/productService"; import { listCustomers,type Customer } from "../../services/customerService"; import { listCashBoxes,type CashBox } from "../../services/cashboxService"; import { addCartItem,checkout,createCart,deleteCartItem,listOrders,updateCartCustomer,type Cart,type CheckoutPayment,type Order,type PaymentMethod } from "../../services/salesService";
const money=(v:string|number)=>Number(v||0).toLocaleString("fa-IR");
export default function Sales(){
 const {activeStore,activeRole}=useStore(); const [products,setProducts]=useState<Product[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [cashboxes,setCashboxes]=useState<CashBox[]>([]); const [cart,setCart]=useState<Cart|null>(null); const [orders,setOrders]=useState<Order[]>([]); const [product,setProduct]=useState<Product|null>(null); const [barcode,setBarcode]=useState(""); const [quantity,setQuantity]=useState("1"); const [discount,setDiscount]=useState("0"); const [customerId,setCustomerId]=useState<number|null>(null); const [method,setMethod]=useState<PaymentMethod>(activeRole==="seller"?"credit":"cash"); const [payments,setPayments]=useState<CheckoutPayment[]>([]); const [cashboxId,setCashboxId]=useState<number|"">(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
 const refresh=async(id:number)=>{const [p,c,b,o]=await Promise.all([listProducts(id),listCustomers(id),listCashBoxes(id),listOrders(id)]);setProducts(p.filter(x=>x.is_active!==false));setCustomers(c);setCashboxes(b);setOrders(o);if(!cashboxId&&b.length)setCashboxId(b[0].id);};
 useEffect(()=>{if(!activeStore)return;setLoading(true);setError("");void refresh(activeStore.id).catch(e=>{console.error(e);setError("خطا در دریافت اطلاعات فروشگاه");}).finally(()=>setLoading(false));},[activeStore]);
 const total=Number(cart?.total_price||0),paid=payments.reduce((s,p)=>s+Number(p.amount||0),0),remaining=total-paid,selectedCustomer=customers.find(c=>c.id===customerId)||null;
 const ensureCart=async()=>{if(cart)return cart;if(!activeStore)throw new Error("store");const c=await createCart(activeStore.id,customerId);setCart(c);return c;};
 const add=async()=>{if(!product&&!barcode.trim()){setError("یک کالا انتخاب کنید یا بارکد را وارد کنید.");return;}try{setSaving(true);setError("");const c=await ensureCart();const item=await addCartItem(c.id,{...(product?{product:product.id}:{barcode:barcode.trim()}),quantity,discount_percent:discount});const items=c.items.some(x=>x.id===item.id)?c.items.map(x=>x.id===item.id?item:x):[...c.items,item];setCart({...c,items,total_before_discount:String(items.reduce((s,x)=>s+Number(x.total_price_before_discount),0)),total_discount:String(items.reduce((s,x)=>s+Number(x.total_discount_amount),0)),total_price:String(items.reduce((s,x)=>s+Number(x.total_price),0))});setProduct(null);setBarcode("");setQuantity("1");setDiscount("0");setPayments([]);}catch(e){console.error(e);setError("افزودن کالا به سبد انجام نشد.");}finally{setSaving(false);}};
 const changeCustomer=async(id:number|null)=>{setCustomerId(id);if(!cart)return;try{setCart(await updateCartCustomer(cart.id,id));}catch{setError("تغییر مشتری انجام نشد.");}};
 const remove=async(id:number)=>{if(!cart)return;try{await deleteCartItem(cart.id,id);const items=cart.items.filter(x=>x.id!==id);setCart({...cart,items,total_before_discount:String(items.reduce((s,x)=>s+Number(x.total_price_before_discount),0)),total_discount:String(items.reduce((s,x)=>s+Number(x.total_discount_amount),0)),total_price:String(items.reduce((s,x)=>s+Number(x.total_price),0))});setPayments([]);}catch{setError("حذف کالا انجام نشد.");}};
 const addPayment=()=>{if(remaining<=0)return;setPayments(p=>[...p,{method,amount:remaining.toFixed(2),cashbox_id:method==="credit"?null:Number(cashboxId)}]);};
 const doCheckout=async()=>{if(!cart||!cart.items.length){setError("سبد فروش خالی است.");return;}if(!payments.length||Math.abs(remaining)>0.009){setError("مجموع پرداخت‌ها باید دقیقاً برابر مبلغ سفارش باشد.");return;}if(payments.some(p=>(p.method==="cash"||p.method==="card")&&!p.cashbox_id)){setError("برای پرداخت نقدی یا کارتخوان صندوق الزامی است.");return;}if(payments.some(p=>p.method==="credit")&&!customerId){setError("فروش حسابی بدون مشتری مجاز نیست.");return;}try{setSaving(true);setError("");const r=await checkout(cart.id,payments);setSuccess(`فروش شماره ${r.id} با موفقیت ثبت شد.`);setCart(null);setPayments([]);setCustomerId(null);if(activeStore)await refresh(activeStore.id);}catch(e){console.error(e);setError("ثبت فروش انجام نشد. اطلاعات پرداخت و موجودی را بررسی کنید.");}finally{setSaving(false);}};
 if(!activeStore)return <Alert severity="warning">ابتدا یک فروشگاه انتخاب کنید.</Alert>; if(loading)return <Box sx={{display:"grid",placeItems:"center",minHeight:300}}><CircularProgress/></Box>;
 return <Box dir="rtl"><Typography variant="h5" sx={{mb:2}}>ثبت فروش</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{success&&<Alert severity="success" sx={{mb:2}}>{success}</Alert>}<Stack spacing={2}>
 <Card><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{alignItems:"center"}}><Autocomplete sx={{minWidth:280,flex:1}} options={products} value={product} getOptionLabel={x=>`${x.name}${x.barcode?` — ${x.barcode}`:""}`} onChange={(_,v)=>setProduct(v)} renderInput={p=><TextField {...p} label="کالا"/>}/><TextField label="بارکد" value={barcode} onChange={e=>setBarcode(e.target.value)}/><TextField label="تعداد" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} sx={{width:110}}/><TextField label="تخفیف %" type="number" value={discount} onChange={e=>setDiscount(e.target.value)} sx={{width:110}}/><Button variant="contained" startIcon={<AddShoppingCartIcon/>} onClick={()=>void add()} disabled={saving}>افزودن</Button></Stack></CardContent></Card>
 <Card><CardContent><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{alignItems:"center"}}><Autocomplete sx={{minWidth:300,flex:1}} options={customers} value={selectedCustomer} getOptionLabel={x=>`${x.first_name} ${x.last_name} — ${x.mobile}`} onChange={(_,v)=>void changeCustomer(v?.id??null)} renderInput={p=><TextField {...p} label="مشتری"/>}/><Typography>مبلغ نهایی: <strong>{money(total)}</strong></Typography></Stack></CardContent></Card>
 <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>کالا</TableCell><TableCell>تعداد</TableCell><TableCell>قیمت</TableCell><TableCell>تخفیف</TableCell><TableCell>جمع</TableCell><TableCell/></TableRow></TableHead><TableBody>{(cart?.items||[]).map(i=><TableRow key={i.id}><TableCell>{i.product_name}</TableCell><TableCell>{i.quantity}</TableCell><TableCell>{money(i.unit_price)}</TableCell><TableCell>{i.discount_percent}%</TableCell><TableCell>{money(i.total_price)}</TableCell><TableCell><IconButton onClick={()=>void remove(i.id)}><DeleteIcon/></IconButton></TableCell></TableRow>)}{(!cart||!cart.items.length)&&<TableRow><TableCell colSpan={6} align="center">سبد فروش خالی است.</TableCell></TableRow>}</TableBody></Table></TableContainer>
 <Card><CardContent><Typography variant="h6" sx={{mb:2}}>پرداخت</Typography><Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{alignItems:"center"}}><Select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}>{(activeRole==="seller"?["credit"]:["cash","card","credit"]).map(m=><MenuItem key={m} value={m}>{m==="cash"?"نقدی":m==="card"?"کارتخوان":"حسابی"}</MenuItem>)}</Select>{(method==="cash"||method==="card")&&<Select value={cashboxId} onChange={e=>setCashboxId(Number(e.target.value))} displayEmpty><MenuItem value="" disabled>انتخاب صندوق</MenuItem>{cashboxes.map(b=><MenuItem key={b.id} value={b.id}>{b.name} — {money(b.balance)}</MenuItem>)}</Select>}<Typography>باقی‌مانده: <strong>{money(Math.max(remaining,0))}</strong></Typography><Button variant="outlined" startIcon={<PaymentIcon/>} onClick={addPayment} disabled={!cart||remaining<=0}>افزودن پرداخت</Button><Button variant="contained" color="success" startIcon={<ReceiptLongIcon/>} onClick={()=>void doCheckout()} disabled={saving||!cart||!cart.items.length||!payments.length||Math.abs(remaining)>0.009}>ثبت نهایی</Button></Stack>{payments.map((p,i)=><Paper key={i} variant="outlined" sx={{p:1,mt:1,display:"flex",justifyContent:"space-between"}}><span>{p.method==="cash"?"نقدی":p.method==="card"?"کارتخوان":"حسابی"} — {money(p.amount)}</span><Button size="small" color="error" onClick={()=>setPayments(x=>x.filter((_,j)=>j!==i))}>حذف</Button></Paper>)}</CardContent></Card>
 <Typography variant="h6">آخرین فروش‌ها</Typography><TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>شماره</TableCell><TableCell>مشتری</TableCell><TableCell>مبلغ</TableCell><TableCell>وضعیت</TableCell><TableCell>تاریخ</TableCell></TableRow></TableHead><TableBody>{orders.slice(0,10).map(o=><TableRow key={o.id}><TableCell>{o.id}</TableCell><TableCell>{o.customer_name||"مشتری نقدی"}</TableCell><TableCell>{money(o.total_price)}</TableCell><TableCell>{o.status==="paid"?"پرداخت شده":o.status==="cancelled"?"لغو شده":o.status==="confirmed"?"تأیید شده":"در انتظار"}</TableCell><TableCell>{o.created_at}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
 </Stack></Box>;
}
