import {useEffect,useState} from "react";
import {Alert,Box,Button,Card,CardContent,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Select,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from "@mui/material";
import DeleteIcon from "@mui/icons-material/Delete";
import {useStore} from "../../contexts/StoreContext";
import {listProducts,type Product} from "../../services/productService";
import {createPrice,deletePrice,listPrices,type ProductPrice,type PriceType} from "../../services/pricingService";
import JalaliDateInput from "../../components/JalaliDateInput";
import {jalaliDateToLocalIso} from "../../utils/jalaliDate";

const money=(v:string|number)=>Number(v||0).toLocaleString("fa-IR");
const dateLabel=(v?:string|null)=>v?new Date(v).toLocaleString("fa-IR-u-ca-persian",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"بدون پایان";
const err=(e:any)=>{const d=e?.response?.data;if(typeof d?.detail==="string")return d.detail;if(typeof d?.message==="string")return d.message;if(typeof d==="string")return d;if(d&&typeof d==="object"){for(const [,v] of Object.entries(d)){if(typeof v==="string")return v;if(Array.isArray(v)&&typeof v[0]==="string")return v[0];if(v&&typeof v==="object"){const nested=Object.values(v as Record<string,unknown>);const text=nested.find(x=>typeof x==="string");if(typeof text==="string")return text;}}}return "عملیات انجام نشد.";};

export default function Pricing(){
 const {activeStore}=useStore(); const [products,setProducts]=useState<Product[]>([]); const [prices,setPrices]=useState<ProductPrice[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<Product|null>(null); const [type,setType]=useState<PriceType>("retail"); const [amount,setAmount]=useState(""); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [saving,setSaving]=useState(false);
 const load=async()=>{if(!activeStore)return;setLoading(true);try{const[p,pr]=await Promise.all([listProducts(activeStore.id),listPrices(activeStore.id)]);setProducts(p.filter(x=>x.is_active!==false));setPrices(pr);}catch(e){setError(err(e));}finally{setLoading(false);}};
 useEffect(()=>{void load()},[activeStore?.id]);
 const save=async()=>{if(!activeStore||!selected){setError("کالا را انتخاب کنید.");return;}const n=Number(amount);if(!Number.isFinite(n)||n<=0){setError("مبلغ باید بزرگ‌تر از صفر باشد.");return;}if(from&&!jalaliDateToLocalIso(from))return setError("تاریخ شروع شمسی نامعتبر است.");if(to&&!jalaliDateToLocalIso(to,true))return setError("تاریخ پایان شمسی نامعتبر است.");if(from&&to&&new Date(jalaliDateToLocalIso(from)!)>=new Date(jalaliDateToLocalIso(to,true)!)){setError("پایان اعتبار باید بعد از شروع اعتبار باشد.");return;}try{setSaving(true);setError("");await createPrice({product:selected.id,store:activeStore.id,price_type:type,amount:n.toFixed(2),effective_from:from?jalaliDateToLocalIso(from):undefined,effective_to:to?jalaliDateToLocalIso(to,true):null,is_active:true});setOpen(false);setAmount("");setFrom("");setTo("");await load();}catch(e){setError(err(e));}finally{setSaving(false);}};
 const remove=async(id:number)=>{if(!confirm("این قیمت حذف شود؟"))return;try{await deletePrice(id);await load();}catch(e){setError(err(e));}};
 if(!activeStore)return <Alert severity="warning">ابتدا فروشگاه را انتخاب کنید.</Alert>;
 return <Box dir="rtl"><Stack direction={{xs:"column",sm:"row"}} sx={{mb:2,justifyContent:"space-between",alignItems:"center"}}><Box><Typography variant="h5" sx={{fontWeight:700}}>قیمت‌گذاری حرفه‌ای</Typography><Typography color="text.secondary">قیمت‌ها بر اساس نوع، فروشگاه و بازه زمانی مدیریت می‌شوند.</Typography></Box></Stack>{error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError("")}>{error}</Alert>}{loading?<CircularProgress/>:<Card><CardContent><Table size="small"><TableHead><TableRow><TableCell>کالا</TableCell><TableCell>قیمت پایه</TableCell><TableCell>قیمت جاری</TableCell><TableCell>بازه‌ها و وضعیت</TableCell><TableCell>عملیات</TableCell></TableRow></TableHead><TableBody>{products.map(p=>{const ps=prices.filter(x=>x.product===p.id);const current=ps.filter(x=>x.is_current);const currentRetail=current.find(x=>x.price_type==="retail");return <TableRow key={p.id}><TableCell><strong>{p.name}</strong></TableCell><TableCell>{money(p.sale_price||0)}</TableCell><TableCell>{money(currentRetail?.amount||p.sale_price||0)} {currentRetail&&<Chip size="small" sx={{mr:.5}} label="فعال"/>}</TableCell><TableCell>{ps.length?ps.map(x=><Chip key={x.id} size="small" sx={{mr:.5,mb:.5}} color={x.is_current?"success":x.is_active?"default":"warning"} label={`${x.price_type_display} ${money(x.amount)} | ${dateLabel(x.effective_from)} تا ${dateLabel(x.effective_to)}`} onDelete={()=>void remove(x.id)} deleteIcon={<DeleteIcon/>}/>):"قیمتی تعریف نشده؛ فروش با قیمت پایه انجام می‌شود."}</TableCell><TableCell><Button size="small" variant="outlined" onClick={()=>{setSelected(p);setType("retail");setOpen(true)}}>قیمت جدید</Button></TableCell></TableRow>})}{!products.length&&<TableRow><TableCell colSpan={5} align="center">کالایی برای قیمت‌گذاری وجود ندارد.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>}
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>قیمت جدید — {selected?.name}</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><Select value={type} onChange={e=>setType(e.target.value as PriceType)}><MenuItem value="retail">خرده‌فروشی</MenuItem><MenuItem value="wholesale">عمده‌فروشی</MenuItem><MenuItem value="special">ویژه</MenuItem></Select><TextField label="مبلغ" type="number" value={amount} onChange={e=>setAmount(e.target.value)} slotProps={{htmlInput:{min:0}}}/><JalaliDateInput label="شروع اعتبار (اختیاری؛ خالی = از لحظه ثبت)" value={from} onChange={setFrom}/><JalaliDateInput label="پایان اعتبار (اختیاری)" value={to} onChange={setTo} allowClear/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={saving}>انصراف</Button><Button variant="contained" onClick={()=>void save()} disabled={saving}>ثبت قیمت</Button></DialogActions></Dialog></Box>;
}
