# Generated by Django 6.1 on 2026-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='تعداد'),
        ),
    ]
