# Generated by Django 6.1 on 2026-08-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0008_cashbox_cashboxtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sales.cashbox'),
        ),
        migrations.AddConstraint(
            model_name='cashbox',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_cashbox_name_per_store'),
        ),
    ]
