# Generated by Django 6.1 on 2026-08-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_expense_cashbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cashbox',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sales.cashbox'),
            preserve_default=False,
        ),
    ]
