# Generated by Django 6.1 on 2026-08-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='موجودی')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='حداقل موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product', verbose_name='کالا')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='core.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'موجودی کالا',
                'verbose_name_plural': 'موجودی کالاها',
                'constraints': [models.UniqueConstraint(fields=('product', 'store'), name='unique_product_store_inventory')],
            },
        ),
    ]
