# Generated by Django 6.1 on 2026-08-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_supplier_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
